### ISSUE TITLE
Target or URI doesn't exist for the package

### ISSUE THREAD

**Issue by XtremeTheory** [benhurott/flutter-masked-text#1]
Error trying to retrieve the package.  Any ideas?

**Comment by bhrott** [comment]
To let me analyse, send:
* The error stack trace, not only title.
* Your `pubspec.yaml` dependencies section to let me review you install it's correctly.

I tried to create a new app and follow the installation guide. It works to me.

**Comment by bhrott** [comment]
Hi, i'm closing this.
If the issue persist, please, reopen.
