### ISSUE TITLE
Is there any CPF and CNPJ validator?

### ISSUE THREAD

**Issue by alvarolordelo** [benhurott/flutter-masked-text#14]
I'd like to have the CPF and CNPJ validator working on that package if it's possible, thanks!

**Comment by bhrott** [comment]
Hi @alvarolordelo !

This package is only for masked values.
Custom validators for specific business rules are no longer part of the roadmap.

But this is a good idea for an external package! =)

**Comment by alvarolordelo** [comment]
Masks but don't validate?
It's a one time implementation

**Comment by bhrott** [comment]
Yes man, I understand.
But think: CPF and CNPJ are Brazilian rules and the purpose of this project is only to mask the input, not apply specific rules.
You can always create a custom package for it (that's one time implementation, like you said). You can create gists or (better) a external package.
