### ISSUE TITLE
Add currency symbol to MoneyMaskedTextController

### ISSUE THREAD

**Issue by tobire** [benhurott/flutter-masked-text#2]
It would be awesome to have a currency symbol (like € or $) automatically inserted after a money input using the MoneyMaskedTextController.

Hope you can implement this,
thanks for the great plugin!

**Comment by bhrott** [comment]
Hi,

I will work on this =).

Tks!

**Comment by bhrott** [comment]
Done!

Now it's available in `0.5.0`.
