### ISSUE TITLE
Disable minus symbol on MoneyMaskedTextController

### ISSUE THREAD

**Issue by tobire** [benhurott/flutter-masked-text#3]
When using the MoneyMaskedTextController with the number keyboard (keyboardType: TextInputType.number) it is possible to enter minus symbols which get appended to the number.

From my point of view, that should not be the case for a money input.

**Comment by tobire** [comment]
Also, after a minus is entered, the following numbers get written after that minus.
However, this will probably fixed automatically, if there is no way to enter a minus.

**Comment by bhrott** [comment]
Fixed at `0.4.1`.

Thanks for reporting.
