### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by andredealmei** [benhurott/flutter-masked-text#30]
flutter_masked_text: ^0.8.0
If you long press to select a number masked input and then try to key got this error

RangeError: Invalid value: Not in range 0..1, inclusive: -1

![Screenshot_20190514-115440](https://user-images.githubusercontent.com/33403972/57708254-6588eb80-763f-11e9-9e8c-9df07c21b19f.png)

![screen-11 58 03 14 05 2019](https://user-images.githubusercontent.com/33403972/57708351-8cdfb880-763f-11e9-8b23-29d79e4cbbfe.png)

**Comment by andredealmei** [comment]
Update: You can dodge the error defining **enableInteractiveSelection: false** on **textField**

**Comment by bhrott** [comment]
HI @andredealmei , could you provide a code sample?

**Comment by bhrott** [comment]
Closing due inactivity.
If the issue persists, let me know but please provide a code sample. =)
