### ISSUE TITLE
Necessário retornar o valor sem máscara no validator

### ISSUE THREAD

**Issue by Katekko** [benhurott/flutter-masked-text#35]
Acho que seria necessário retornar o valor sem mascara no (val) para que consiga validar corretamente!

![image](https://user-images.githubusercontent.com/13632735/62213103-90e6c100-b378-11e9-8c0d-dfa9d9f1a83f.png)

**Comment by bhrott** [comment]
Hi, you can get the `numberValue` of the controller:

https://github.com/benhurott/flutter-masked-text#get-double-value

**Comment by Katekko** [comment]
Isso eu sei, mas não sei se seria certo utilizar o valor do controller ao invés de pegar o retorno da função no validator... O fluxo deveria seguir o da função e retornar o valor sem mascara para validar. Pelo menos eu acho
