### ISSUE TITLE
Invalid double in numberValue when delete value in TextFormField

### ISSUE THREAD

**Issue by hassanbht** [benhurott/flutter-masked-text#39]
Hello,
I'm getting this error in my MoneyMaskedTextController when clear  TextFormField
error : Type (FormatException) "Invalid double" 

double get numberValue {
    List<String> parts = _getOnlyNumbers(this.text).split('').toList(growable: true);
    parts.insert(parts.length - precision, '.'); // value : "." 
    return double.parse(parts.join());
  }

**Comment by x4080** [comment]
Hi, @hassanbht 

How do you solve this problem >?

**Comment by phungrk** [comment]
@x4080 

https://github.com/benhurott/flutter-masked-text/pull/24

**Comment by joaovirgili** [comment]
I'm getting this error when calling clear() on MoneyMaskedTextController:

The following RangeError was thrown while dispatching notifications for MoneyMaskedTextController:
Invalid value: Only valid value is 0: -2

**Comment by denyjav** [comment]
Were you able to solve this problem?
